G_LNG_ZH={
    "Lang" : "zh-CN",
    "OK": "确定",
    "Cancel": "取消",
    "Home":"首页",
    "LogOut":"登出",
    "Modify":"修改",
    "Delete":"删除",
    "TipTitle":"提示",
    "CreatNew":"添加",
    "CreatCopy":"新建",
    "ModifyTemplate":"修改模板名称",
    "EmptyTip":"不能为空",
    "LocalName":"管理员",
    "Title":"ICD访客管理系统",
    "LoadingTip":"加载中...",
    "Login":{
        "Title":"ICD访客管理系统",
        "Login":"登录",
        "UserName":"用户名",
        "Password":"密码",
        "ValidCode":"验证码"
    },
    "Route": {
        "Dashboard": "首页",
        "History":"记录查询",
            "Approve":"预约审批",
        "Configuration": "系统配置",
            "Basis":"基础配置",
            "VMSFront":"访客配置",
            "Users":"用户管理",
            "VisitType": "数据字段",
            "National": "国家地区",
            "DataBridge":"数据对接",
            "ActiveDirectory":"域校验",
            "RiskRegions":"风险地区",
        "Administrator":"管理员",
            "VisitPlace": "来访地点",
            "Email": "邮件",
            "Message": "短信",
       "Management":"数据管理",
            "Record":"快递类型",
            "RegistrationRecord":"预约查询",
            "Visitor":"访客名单",
            "Host":"员工名单",
            "Employee":"门禁数据",
            "Blacklist":"黑名单",
            "Whitelist":"白名单",
        "Server":"服务器数据",
            "Log":"日志"
    },
    "Common":{
        "Invaild":"已失效",
        "Vaild":"待访问",
        "Visited":"已到访",
        "ReSendTextMessage":"重新发送短信",
        "CancelRegister":"取消预约",
        "NotSend":"未发送",
        "Sendtips":"短信发送次数",
        "MessageStatusV":"访客短信状态",
        "MessageStatusH":"员工短信状态",
        "ResendTips":"是否重新发送",
        "CancelTips":"是否取消预约",
        "SendSuccess":"发送成功",
        "SendFailed":"发送失败",
        "CancelSuccess":"取消成功",
        "CancelFailed":"取消失败",
        "HasCancel":"已取消",
        "Sending":"发送中",
        "Rejected":"已拒绝",
        "RemoveBlackList":"移出黑名单",
        "RemoveWhiteList":"移出白名单",
        "WaitApprove":"待审批",
        "GoApprove":"去审批",
        "ApproveTip":"是否批准",
        "RejectTip":"是否拒绝",
        "ApproveMessage":"批准",
        "RejectMessage":"拒绝",
        "ApproveSuccess":"审批成功",
        "ApproveFailed":"审批失败",
        "Approved":"已批准",
        "RejectReason":"拒绝原因(选填)",
        "GroupApproveMessage":"全部批准",
        "GroupRejectMessage":"全部拒绝",
        "GroupCancelRegister":"全部取消",
        "ApproveAllTip":"是否全部批准",
        "RejectAllTip":"是否全部拒绝",
        "CancelAllTips":"是否全部取消",
        "Remark":"备注",
        "COVID-19":"COVID-19"
    },
    "dashboard":{
        "RegistrationTitle":"未到访",
        "SignInTitle":"已到访",
        "SignOutTitle":"已签出",
        "WaitforApproveTitle":"待审批",
        "Receive":"收件",
        "Registration":"预约",
        "SignIn":"签到",
        "SignOut":"签出",
        "Approve":"通过",
        "Reject":"拒绝",
        "WaitforHost":"待接待",
        "BatchSignIn":"批量签入",
        "OperatingPrint":"打印",
        "OperatingSignin":"签入",
        "OperatingSignout":"签出",
        "CheckAll":"全选",
        "RegCode":"预约码",
        "VisitorName":"访客姓名",
        "Email":"Email",
        "VisitorIDType":"证件类型",
        "VisitorID":"证件号码",
        "VisitorUnit":"单位",
        "PhoneNumber":"手机号",
        "VistPurpose":"来访原因",
        "HostName":"员工姓名",
        "HostDepartment":"部门",
        "VisitPlace":"来访地点",
        "Keyword":"关键字",
        "VisitorInfo":"来访信息",
        "VisitorsInfo":"访客信息",
        "HostInfo":"员工信息",
        "Passport":"护照",
        "IDCard":"身份证",
        "OtherID":"其他",
        "BatchSignOut":"批量签出",
        "SigninSuccess":"签到成功",
        "SigninFailed":"签到失败",
        "SignoutSuccess":"签出成功",
        "SignoutFialed":"签出失败",
        "SigninTime":"签入时间",
        "SigninPonint":"签入地点",
        "SignoutTime":"签出时间",
        "SignoutPonint":"签出地点",
        "Total":"总计",
        "TotalTitle":"全部",
        "ActualHost":"实际接访人",

        "PrintSuccess":"打印成功",
        "PrintFailed":"打印失败",
        "ViewImage":"查看图片",
        "KeepInfo":"其他信息",
        "NotFoundIP":"未找到打印机IP",
        "TodayVisitCount":"今日访客",
        "WeekVisitCount":"过去七日访客",
        "FuntureVisitorCount":"未来七日访客",
        "UpdateTime":"最后更新时间",
        "CheckTip":"请勾选访客记录"
    },
    "Configuration":{
        "VisitPlace":{
            "SMSEnable":"启用短信通知",
            "SMSServiceName":"短信服务名称",
            "SMSTemplateGroupName":"短信模板组名称",
            "EmailEnable":"启用邮件通知",
            "EmailAccountName":"SMTP服务",
            "EmailTemplateGroupName":"邮件模板组",
            "BranchName":"唯一编码",
            "LocalName":"地点名称(2)",
            "EnName":"地点名称",
            "CreateSMSService":"新建短信服务",
            "CreateSMSTemplate":"新建短信模板",
            "CreateSMSTempalteGroup":"新建短信模板组",
            "CreateEmailService":"新建SMTP服务",
            "CreateEmailTemplate":"新建邮件模板",
            "CreateEmailTempalteGroup":"新建邮件模板组",
            "VisitPlace":"来访地点",
            "CreateVisitPlace":"新建来访地点",
            "TimerArea":"时区",
            "EditVisitPlace":"编辑来访地点",
            "AddressCN":"详细地址(2)",
            "AddressEN":"详细地址",
            


            "TipBranchEmpty":"请输入地点编码",
            "TipLocalNameEmpty":"请输入名字(本地)",
            "TipEnNameEmpty":"请输入名字(英文)",
            "TipSMSServiceEmpty":"请选择短信服务",
            "TipSMSTemplateGroupEmpty":"请选择短信模板组",
            "TipEmailServiceEmpty":"请选择Email服务",
            "TipEmailTemplaetGroupEmpty":"请选择邮件模板组",
            "TipBranchLong":"地点编码过长",
            "FailedSvaeVPlace":"保存来访地点失败！",
            "FailedGetVPlace":"获取来访地点失败!",
            "SelectNationTip":"请选择国家/地区",
            "BranchOnlyTip":"该地点编码已存在，请重新输入",
            "BranchOnlyTip2":"地点编码为唯一值",
            "TimeZone":"时区",
            "SelectTimeZone":"请选择时区"
        },
        "Email":{
            "ServerName":"SMTP服务器IP",
            "ServerPort":"SMTP服务器端口",
            "Account":"发件箱账户",
            "PassWord":"发件箱密码",
            "Enable":"启用发送电子邮件",
            "SenderName": "发件人名称",
            "From": "From",
            "EmailSubject": "邮件主题",
            "SendTestEmail": "发送测试Email",
            "ID": "ID",
            "EmalilService": "SMTP",
            "Email":"Email",
            "CreateEmailService":"新建SMTP服务",
            "EmailRemark":"SMTP服务",
            "EditEmailService":"编辑SMTP服务",
            "EmailServiceName":"SMTP服务名称",
            "EmailSecurityType":"SMTP加密类型",
            "EmailAuthenticate":"发件箱验证",
            "NoSecurity":"不进行加密",
            "TLSSecurity":"TLS 加密",
            "SSLSecurity":"SSL 加密",

            "EmailTemplate":"邮件模板",
            "EmailTemplateName":"模板名称",
            "CreateEmailTemplate":"新建邮件模板",
            "EmailTemplateType":"模板类型",
            "EmailTemplateContent":"邮件正文",
            "EditEmailTemplate":"编辑邮件模板",
            "EmailTemplateLanType":"模板语言",

            "EmailTemplateGroup":"邮件模板组",
            "CreateTemplateGroup": "新建邮件模板组",
            "EmailTemplateGroupName":"模板组名称",
            "EmailTemplaetGroupRemark":"备注",
            "EditEmailTemplateGroup":"编辑邮件模板组",
            "EmailDefault":"默认SMTP服务",
            "TemplateGroupTitleLeft":"模板列表",
            "TemplateGroupTitleRight":"已选",

            "EmailTipServerNameEmpty":"输入SMTP服务器IP",
            "EmailTipServerPortEmpty":"输入SMTP服务器端口",
            "EmailTipEmailRemarkEmpty":"输入SMTP服务名称",
            "EmailTipAccountEmpty":"输入发件箱账户",
            "EmailTipPassWordEmpty":"输入发件箱密码",
            "EmailTipSecurityTypeEmpty":"选择SMTP加密类型",
            "EmailTipSenderNameEmpty":"输入发件人名称",
            "EmailTipFromEmpty":"输入From",
            "EmailTipEmailSubjectEmpty":"输入邮件主题",

            "EmailTipTemplateName":"输入模板名称",
            "EmailTipTemplateType":"请选择模板类型",
            "EmailTipTemplateLanguage":"请选择模板语言",
            "EmailTipTemplateContent":"请输入模板内容",
            "EmailTipTemplateGroupName":"请输入模板组名称",
            "EmaliTipTemplateGroupRemark":"请输入模板组备注",
            "EmailTipErrorPort":"请输入正确的SMTP服务器端口",
            "SelectSecurityType":"请选择邮件加密类型",
            "SelectTemplateType":"请选择邮件模板类型",
            "TemplateENEmpty":"请输入英文模板"
        },
        "SMS":{
            "MessageService":"短信类型",
            "AppID":"App ID (CN)",
            "AppKey":"App Key (CN)",
            "Signature":"短信签名",
            "AppIDINT":"App ID",
            "AppKeyINT":"App Key",
            "Enable":"发送短信通知",
            "SendTestMessage": "发送测试短信",
            "TestPhoneNumber": "手机号",
            "ServiceRemark": "短信服务",
            "TemplateType": "模板类型",
            "TemplateLanguage": "语言",
            "TemplateKeyWord": "关键字",
            "ServiceID": "短信服务名称",
            "PhoneNumber": "手机号",
            "CreateService": "新建短信服务",
            "ID": "ID",
            "SMSDefault":"默认短信服务",

            "TemplateID": "短信模板名称",
            "CreateTemplate": "新建短信模板",
            "TemplateRemark": "模板名称",
            "TemplateContent": "模板内容",
            "EditService":"编辑短信服务",
            "EditTemplate":"编辑短信模板",
            "Service": "短信服务",
            "Template": "短信模板",
            "TemplateDescrption":"短信模板描述",
            "TemplateCNContent":"中文模板",
            "TemplateEnContent":"英文模板 (*)",
            "TemplateJaContent":"日文模板",
            "TemplateKoContent":"韩文模板",

            "TemplateGroup": "短信模板组",
            "CreateTeplateGroup": "新键短信模板组",
            "TemplateGroupName": "模板组名称",
            "TemplateGroupRemark": "备注",
            "EditTemplateGroup":"编辑短信模板组",

            "SMSChanalEmpty":"请选择短信服务",
            "SMSAppIDEmpty":"请输入App ID",
            "SMSAppKeyEmpty":"请输入App Key",
            "SMSAppIDExtEmpty":"请输入App ID(INT.)",
            "SMSAppKeyExtEmpty":"请输入App Key(INT.)",
            "SMSAppTip":"请输入App ID或App ID(cn)",
            "SMSSignatureEmpty":"请输入短信签名",
            "SMSNameEmpty":"请输入服务名称",
            "SMSTemplateType":"请选择模板类型",
            "SMSTemplateLanguage":"请选择模板语言",
            "SMSTemplateContent":"请输入模板内容",
            "SMSTemplateName":"请输入模板名称",
            "SMSTemplateGroupName":"请输入短息模板组名称",
            "SMSTemplateGroupDes":"请输入模板组描述",
            "SelectTemplateType":"请选择短信模板类型"

        },
        "DataBridge":{
            "Title":"数据对接",
            "Enable":"启用与门禁系统交换数据",
            "DataBridgeServiceIP":"服务IP",
            "DataBridgeServicePort":"服务端口",
            "VerifyInformation":"使用门禁系统验证持卡人信息",
            "TimetoSynchronize":"同步时间",
            "TimeIntervaltoretry":"重试时间间隔",
            "AssignVisitorCard":"自动分配访客卡权限",
            "VisitorCardType":"访客卡类型",
            "RangeofQRcodeBadgeID":"QR-Code取值范围",
            "QRCodeCanOpenDoor":"SMS中的QR-Code可用于直接开门",
            "BadgeType":"卡类型",
            "BadgeStatus":"卡状态",
            "UseLimit":"使用限制",
            "DefaultAccessLevel":"默认权限",
            "AccessLevelTimeperiod":"访问时间段",
            "ExchangeDataViaICD":"通过ICD DataRelayService进行数据对接",
            "StartTime":"起始时间",
            "EndTime":"结束时间",
            "SelectTime":"选择时间",

            "Timeperiod1":"基于预约",
            "Timeperiod2":"用户指定",
            "Timeperiod3":"基于权限等级"
            
        },
        "ActiveDirectory":{
            "Title":"域校验",
            "Enable":"启用域校验",
            "DomainName":"域名"
        },
        "Basis":{
            "Title":"基础配置",
            "RegCodeNumber":"预约码",
            "DataBaseInstanceName":"数据库服务器名称",
            "DataBaseKeepDays":"数据保存时间",
            "ImageHoldTime":"图像保存时间",
            "Tip":"*修改后请重启服务器" ,
            "30Days":"30 天",
            "90Days" :"90 天",
            "180Days" :"180 天",
            "360Days" :"360 天",
            "540Days" :"540 天",
            "720Days" :"720 天",
            "1080Days" :"1080 天",
            "SavePermanent" :"永久保存",
            "Sixdigits":"6 位",
            "Tendigits":"10 位",
            "SqlEmpty":"数据库实例名不能为空",
            "DataBaseType":"数据库认证",
            "DataBaseUserName":"用户名",
            "DataBasePsw":"密码",
            "DataBaseType1":"Windows 身份验证",
            "DataBaseType2":"SQL Server 身份验证"
        },
        "VMSFront":{
            "ConfigKeywords":"关键字段",
                "VisitorName":"访客姓名",
                "VisitorMobile":"访客电话",
                "VisitorNation":"访客国籍",
                "VisitorDocType":"访客证件类型",
                "VisitorDocIDNum":"访客证件ID",
                "VisitorCompany":"访客公司名称",
                "VisitorEmail":"访客邮箱",
                "HostName":"员工姓名",
                "HostMobile":"员工电话",
                "HostEmail":"员工邮箱",
                "HostDept":"员工所属部门",
                "VisitPlace":"来访地点",
                "VisitPurpose":"来访原因",
                "VisitorPlate":"车牌号",
                "HostID":"员工号",
                "HostDivision":"员工所属区域",
                "VisitorKeywords":"访客关键字段",
                "HostKeywords":"员工关键字段",
                "FieldView":"字段显示",
                "FieldRequire":"字段必填",
                "FieldQuery":"字段查询",
                "FieldType":"字段类型",
                "KeyWords":"关键字段",
                "ConfigPrint":"打印模板",
                "TipFront":"提示字体大小",
                "FirstFront":"名称字体大小",
                "TimeFront":"时间字体大小",
                "ContentFront":"内容字体大小",
                "FacePhotoSite":"人脸坐标",
                "QRcodeSite":"二维码坐标",
                "TipSite":"提示坐标",
                "TimeSite":"时间坐标",
                "Keyword":"关键字段",
                "Type":"类型",
                "Position":"坐标",
                "FontSize":"字体大小",
                "FontStyle":"字体样式",
                "ShowPosition":"效果展示",
                "XPos":"X",
                "YPos":"Y",
                "Width":"W",
                "Height":"H",
                "Alignment":"对齐方式",
                "AlignLeft":"左对齐",
                "AlignRight":"右对齐",
                "AlignCenter":"居中对齐",
                "TypeTip":"请选择类型",
                "KeywordTip":"请选择关键字段",
                "UploadTip":"上传模板图片",
                "TempSize":"模板大小: ",
                "CreatCopy":"复制并新建",
                "CreateElement":"添加区域"

        },
        "VisitorPreRegister":"访客预约，通知访客",
        "HostPreRegister":"访客预约，通知员工",
        "OTP":"短信验证码",
        "ArrivalToVisitor":"访客到达，通知访客",
        "ArrivalToHost":"访客到达，通知员工",
        "RemenderToVisitor":"自动提醒，通知访客",
        "RemenderToHost":"自动提醒，通知员工",
        "SignInToVisitor":"访客签到，通知访客",
        "SignInToHost":"访客签到，通知员工",
        "RegisterReject2V":"拒绝预约，通知访客",
        "RegisterReject2H":"拒绝预约，通知员工",
        "RegisterCancel2V":"取消预约，通知访客",
        "RegisterCancel2H":"取消预约，通知员工",
        "CheckoutVisitor":"访客签出，通知访客",
        "CheckoutHost":"访客签出，通知员工",
        "RegisterApprove2V":"预约审批，通知访客",
        "RegisterApprove2H":"预约审批，通知员工",


        "DefaultTemplate":"默认模板",

        "EMPLOYEENAME":"员工姓名",
        "VISITORNAME":"访客姓名",
        "COMPANY":"访客公司",
        "DATE":"日期",
        "BRANCH_CN":"来访地点(2)",
        "BRANCH_EN":"来访地点",
        "VISITORCOUNTRYCODE":"访客国家区号",
        "VISITORMOBILE":"访客手机号",
        "EMPLOYEEALIAS":"员工授权码",
        "HOSTNAME":"签入地点",
        "REGCODE":"预约码",
        "YEAR":"年份",

        "Save":"保存",
        "Operating": "操作",
        "Edit": "编辑",
        "Delete": "删除",

        "BranchFormatError":"地点编码格式错误",
        "SaveSuccess":"保存成功",
        "SaveFailed":"保存失败" ,
        "DeleteSuccess":"删除成功",
        "DeleteFailed":"删除失败",
        "FailedGetConfiguration":"获取服务器配置失败！",
        "GetSMSInstaceFailed":"获取短信账号失败！",
        "GetEmailInstaceFailed":"获取邮件账号失败！",
        "GetEmailTemplateFailed":"获取邮件模板失败！",
        "GetSMSTemplateFailed":"获取短信模板失败！",
        "GetTempGroupFailed":"获取模板组失败！",
        "NoFeature":"功能未开启！",
        "SendSuccess":"测试发送成功！",
        "SendFailed":"测试发送失败！",
        "SaveSizeFailed":"模板大小不符合"
    },
    "Administrator":{
        "Types":{
            "AddButton":"添加访客类型",
            "TitleA":"添加来访原因",
            "TitleB":"添加员工部门",
            "TitleC":"添加访客类型",
            "TitleAEdit":"修改来访原因",
            "TitleBEdit":"修改员工部门",
            "TitleCEdit":"修改访客类型",
            "Number":"编号",
            "NameCN":"来访原因(2)",
            "NameEN":"来访原因",
            "Operation":"操作",
            "VisitorType":"访客类型",
            "VisitorType2":"访客类型(2)",
            "HostDepartment":"员工部门",
            "HostDepartment2":"员工部门(2)",
            "Purpose":"来访原因",
            "AddDepartment":"添加员工部门",
            "AddPurpose":"添加来访原因",
            "Status":"启用",
            "Enable":"启用",
            "Disable":"禁用",
            "FailedGetVisitorType":"获取访客类型失败！",
            "FailedGetPurpose":"获取来访原因失败！",
            "FailedGetDepartment":"获取员工部门失败！",
            "UpdateSuccess":"更新成功！",
            "CreateSucess":"创建成功！",
            "UpdateFailed":"更新失败！",
            "CreateFailed":"创建失败！",
            "EmptyName":"请输入名称"
        },
        "National":{
            "Title":"国家/地区",
            "CreateNation":"添加国家/地区",
            "NationalCode": "3位编码",
            "NationalCode2": "2位编码",
            "ZHName":"名称(本地)",
            "ENName":"名称",
            "CountryCode":"国家区号",
            "Favourite":"常选项",
            "EditNational":"国家/地区",
            "FailedGetNational":"获取国家/地区失败"
        },
        "Users":{
            "Title":"用户管理",
            "CreateUser":"添加用户",
            "UserName":"用户名",
            "VisitPlaceRights":"来访地点",
            "Descriptions":"描述",
            "AssignedTo":"指派给",
            "EditUsers":"编辑用户",
            "Password":"密码",
            "OldPassword":"旧密码",
            "NewPassword":"新密码",
            "UsersRights":"权限",
            "PrintIP":"打印机 IP",
            "FailedGetUserInfo":"获取用户信息失败！",
            "UserNameEmpty":"请输入用户名",
            "PassWordEmpty":"请输入密码",
            "AssignedEmpty":"请选择用户指派",
            "VisitPlaceEmpty":"请至少选择一个来访地点",
            "TipModify":"下属用户相关配置将一并修改",
            "TipDeleteP":"下属用户将一并删除",
            "TipeDeleteC":"是否确认删除",
            "SelectAllVRoot":"全选查看权限",
            "SelectAllRoot":"全选所有权限",
            "ConfirmPassword":"确认密码",
            "ModifyPassword":"修改密码",
            "Passwordverify":"密码不一致",
            "RightsDocumentID":"证件号权限",
            "PwdCheck":"密码中必须包含字母、数字、特殊字符",
            "PwdRights":"密码自动失效",

            "RightsView":"查看",
            "RightsExport":"导出",
            "RightsCreate":"新建",
            "RightsUpdate":"修改",
            "RightsViewVisitorImage":"查看照片",
            "RightsPrint":"打印",
            "RightsDelete":"删除",
            "RightsList":"权限"

        }
    },
    "Management":{
        "EmptyTime":"查询时间不能为空",
        "MustSelectTime":"请选择查询时间",
        "SelectBranch":"请选择来访地点",
        "ExportTip":"暂无数据",
        "ExportSuccess":"导出成功",
        "Chart":"图表",
        "Table":"表格",
        "AddNew":"创建",
        "ImportData":"导入",
        "LoadFileError":"导入文件出错",
        "ActiveDate":"生效日期",
        "DeactiveDate":"失效日期",
        "LoadSuccess":"导入成功",
        "LoadFailed":"导入失败",
        "DownLoadTemp":"下载模板",
        "LoadHostTip1":"请确认是否导入员工数据，总计：",
        "LoadHostTip2":"条",
        "Record":{
            "RecordTitle":"访客记录",
            "Export":"导出报告",
            "SelectTime":"选择时间",
            "StatusType":"状态",
            "SigninRecord":"已到访",
            "RegisterRecord":"未到访",
            "SignoutRecord":"已签出",
            "AllRecord":"全部",
            "KeywordsRemak":"访客姓名/手机/单位",
            "QueryRecord":"查询",
            "StartDate":"开始日期",
            "EndDate":"结束日期",
            "LastWeek":"最近一周",
            "LastMonth":"最近一个月",
            "RegistrationTime":"日期",
            "BranchChartTitle":"区域访客流量分布",
            "DayChartTitle":"每日访客量统计",
            "ChoseRexportCol":"自定义报表字段",
            "VisitDetial":"来访详情",
            "VisitInfo":"访客信息",
            "HostInfo":"员工信息",
            "Others":"其他",
            "ApplyTime":"提交预约时间",
            "Date":"查询时间",
            "QueryGate":"门禁记录",
            "GateName":"门禁名称"

        },
        "Visitor":{
            "LastHost":"被访员工",
            "LastTime":"最后到访时间",
            "Document":"证件类型",
            "DocumentID":"证件号码",
            "CountryorRegion":"国家/地区",
            "VisitorDetails":"访客信息",
            "VisitDetails":"来访记录",
            "QueryTip":"访客姓名/手机/邮箱/单位",
            "VisitorBadge":"访客卡号"
        },
        "Employee":{
            "Name":"员工姓名",
            "HostNumber":"员工号",
            "HostCardNum":"员工卡号",
            "Division":"区域",
            "OfficePhone":"座机",
            "LastTime":"最后被访时间",
            "LastVisitor":"来访访客",
            "EmployeeDetails":"员工信息",
            "CardDetails":"卡号信息",
            "VisitedDetails":"被访记录",
            "Password":"密码",
            "SaveTip":"请输入密码",
            "CardNumber":"卡号",
            "CardStatus":"卡状态",
            "QueryTip":"员工姓名/手机号/邮箱"
        },
        "List":{
            "VisitorTitle":"访客黑名单",
            "EmployeeTitle":"员工黑名单",
            "VisitorWhiteTitle":"访客白名单",
            "RemoveOut":"移除",
            "RemoveSuccess":"移除成功",
            "RemoveFailed":"移除失败",
            "AddVisitBlack":"加入访客黑名单",
            "AddVisitWhite":"加入访客白名单",
            "AddEmployeeBlack":"加入员工黑名单",
            "AddSuccess":"添加成功",
            "AddFailed":"添加失败"
        }
    },
    "ViewImage":{
        "DialogTitle":"图片信息",
        "ImageTypeV":"访客签到",
        "ImageTypeF":"访客人脸",
        "ImageTypeE":"员工认证",
        "ImageTypeH":"其他 ...",
        "ViewImageError":"查看图片失败"
    },
    "Server":{
        "Time":"日期",
        "Level":"等级",
        "LogContent":"日志内容",
        "AllLog":"全部",
        "Debug":"Debug",
        "Infomaiton":"Information",
        "Warning":"Warning",
        "Error":"Error",
        "Operation":"操作",
        "Length":"长度",
        "Type":"类型"
    },
    "Approve":{
        "Tip":"待审批访客",
        "Other":"其他",
        "Host":"接访人",
        "Visitor":"来访人",
        "status":{
            "label":"状态",
            "valid":"待来访",
            "waitapprove":"待审批",
            "visited":"已到访",
            "cancel":"已取消",
            "reject":"已拒绝",
            "invalid":"已失效",
            "black":"被列入黑名单",
            "Rtimein":"签入时间",
            "Rplacein":"签入地点",
            "Rtimeout":"签出时间",
            "Rplaceout":"签出地点"      
        },
        "checkinfo":"到访信息",
        "details":{
            "title":"详情",
            "cancel":"取消预约",
            "applytime":"提交时间",
            "canceltime":"取消时间",
            "rejecttime":"拒绝时间",
            "passtime":"批准时间",
            "RejectReason":"拒绝原因"
        },
        "RegInfo":{
            "visitInfo":"来访信息",
            "hostInfo":"接访人",
            "visitorInfo":"访客",
            "Vbranch":"来访地点",
            "Vdate":"来访日期",
            "Ename":"员工姓名",
            "Eemail":"邮箱",
            "Vname":"访客姓名",
            "Vunit":"访客单位",
            "Vphone":"手机号",
            "Vpurpose":"来访原因",
            "Vemail":"邮箱",
            "VisitNum":"人",
            "VisitDays":"来访天数",
            "SignleDay":"单天",
            "Days":"天",
            "Nation":"国家",
            "Ephone":"手机号",
            "DocumentID":"证件号",
            "EDept":"员工部门"
        },
        "RiskTip":"存在来自中/高风险地区的访客，是否全部通过"
    },
    "RiskRegisons":{
        "CitySelect":"城市选择",
        "CityTip":"省/市",
        "CountyName":"区/县",
        "CityName":"市",
        "ProvinceName":"省",
        "RiskLevel":"风险等级",
        "LowLevel":"低风险",
        "MidLevel":"中风险",
        "HighLevel":"高风险",
        "MidHighLecel":"中/高风险",
        "BatchEdit":"批量编辑",
        "EditTitle":"风险等级设置",
        "BatchTip":"请选择区域",
        "Tip":"请选择城市",
        "KeyWordsTip":"请至少输入两个关键字"
    },
    "Error":{
        "ErrorCode":"错误码",
        "ErrorPassword":"用户名或密码错误",
        "FailedConnectSQL":"连接数据库失败！",
        "FailedOperateSQL":"操作数据库失败！",
        "VisitorBlack":"访客在黑名单中！",
        "HostBlack":"员工在黑名单中！",
        "NoRecord":"未找到记录！",
        "AlreadyExists":"数据已经存在！",
        "VisitorNoSignin":"未找到访客签到记录！",
        "InvalidData": "无效的数据！",
        "ErrorDataFormat":"错误的数据格式!",
        "InputPswTooMany":"密码错误次数过多",
        "AlreadyExistsDefault":"已经存在默认服务！",
        "OldPasswordError":"旧密码错误！",
        "VaildCodeError":"请输入正确的验证码",
        "PwdExpired":"密码已过期,请重新修改后登录"
    }
}